[package]
name = "game_platform_yew"
version = "0.1.0"
authors = ["Roman <roman.a.shushakov@mail.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yew = "0.17"
wasm-bindgen = "0.2.67"
anyhow = "1"
serde = "1.0.115"
web-sys = "0.3.44"
yew-router = "0.14.0"

