[package]
name = "game_platform"
version = "0.1.0"
authors = ["roman"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0"
actix-rt = "1.0"
actix-files = "0.2"
serde = "1.0"
failure = "0.1.8"
actix-http = "1.0.1"

diesel = { version = "1.4.5", features = ["postgres", "r2d2"] }
dotenv = "0.15.0"
r2d2 = "0.8"

bytes = "0.5"
env_logger = "0.7"
futures = "0.3"
serde_json = "1.0"
uuid = { version = "0.8", features = ["serde", "v4"] }